version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: deleginsumos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  ms-inventario:
    build: ./ms-inventario
    ports:
      - "8001:8001"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://user:password@postgres/deleginsumos
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/

  ms-rrhh:
    build: ./ms-rrhh
    ports:
      - "8003:8003"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres/deleginsumos

  ms-distribucion:
    build: ./ms-distribucion
    ports:
      - "8002:8002"
    depends_on:
      - postgres
      - rabbitmq
    environment:
      DATABASE_URL: postgresql://user:password@postgres/deleginsumos
      RABBITMQ_URL: amqp://guest:guest@rabbitmq/

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8000:8000"
    depends_on:
      - ms-inventario
      - ms-rrhh
      - ms-distribucion

volumes:
  postgres_data: